INSERT INTO examenes(nombre,precio,id_tipo_examen,estado) VALUES ('Audiometria Tonal',100,1,1);
INSERT INTO examenes(nombre,precio,id_tipo_examen,estado) VALUES ('Audiometria Tonal',100,2,1);
INSERT INTO examenes(nombre,precio,id_tipo_examen,estado) VALUES ('Audiometria Tonal',100,3,1);
INSERT INTO examenes(nombre,precio,id_tipo_examen,estado) VALUES ('EEG',100,1,1);
INSERT INTO examenes(nombre,precio,id_tipo_examen,estado) VALUES ('EEG',100,2,1);
INSERT INTO examenes(nombre,precio,id_tipo_examen,estado) VALUES ('EEG',100,3,1);
INSERT INTO examenes(nombre,precio,id_tipo_examen,estado) VALUES ('EEG 1 Hora',100,6,1);
INSERT INTO examenes(nombre,precio,id_tipo_examen,estado) VALUES ('EEG 1 hora',100,7,1);
INSERT INTO examenes(nombre,precio,id_tipo_examen,estado) VALUES ('EEG 1 hra.',100,1,1);
INSERT INTO examenes(nombre,precio,id_tipo_examen,estado) VALUES ('EEG 1 hra.',100,2,1);
INSERT INTO examenes(nombre,precio,id_tipo_examen,estado) VALUES ('EEG 1 hra.',100,3,1);
INSERT INTO examenes(nombre,precio,id_tipo_examen,estado) VALUES ('EEG 1hora',100,4,1);
INSERT INTO examenes(nombre,precio,id_tipo_examen,estado) VALUES ('EEG 2 hrs',100,1,1);
INSERT INTO examenes(nombre,precio,id_tipo_examen,estado) VALUES ('EEG 2 hrs Portatil',100,1,1);
INSERT INTO examenes(nombre,precio,id_tipo_examen,estado) VALUES ('EEG 2 hrs.',100,2,1);
INSERT INTO examenes(nombre,precio,id_tipo_examen,estado) VALUES ('EEG 2 hrs.',100,3,1);
INSERT INTO examenes(nombre,precio,id_tipo_examen,estado) VALUES ('EEG 2 hrs.',100,4,1);
INSERT INTO examenes(nombre,precio,id_tipo_examen,estado) VALUES ('EEG 24 hrs.',100,1,1);
INSERT INTO examenes(nombre,precio,id_tipo_examen,estado) VALUES ('EEG 24 hrs.',100,2,1);
INSERT INTO examenes(nombre,precio,id_tipo_examen,estado) VALUES ('EEG 24 hrs.',100,3,1);
INSERT INTO examenes(nombre,precio,id_tipo_examen,estado) VALUES ('EEG 24 hrs.',100,4,1);
INSERT INTO examenes(nombre,precio,id_tipo_examen,estado) VALUES ('EEG 3 Hrs.',100,3,1);
INSERT INTO examenes(nombre,precio,id_tipo_examen,estado) VALUES ('EEG 4 horas + Glucometria',100,3,1);
INSERT INTO examenes(nombre,precio,id_tipo_examen,estado) VALUES ('EEG 4 hrs.',100,1,1);
INSERT INTO examenes(nombre,precio,id_tipo_examen,estado) VALUES ('EEG 4 hrs.',100,2,1);
INSERT INTO examenes(nombre,precio,id_tipo_examen,estado) VALUES ('EEG 4 hrs.',100,3,1);
INSERT INTO examenes(nombre,precio,id_tipo_examen,estado) VALUES ('EEG 8 horas',100,2,1);
INSERT INTO examenes(nombre,precio,id_tipo_examen,estado) VALUES ('EEG 8 horas',100,3,1);
INSERT INTO examenes(nombre,precio,id_tipo_examen,estado) VALUES ('EEG 8 horas',100,4,1);
INSERT INTO examenes(nombre,precio,id_tipo_examen,estado) VALUES ('EEG 8 horas',100,1,1);
INSERT INTO examenes(nombre,precio,id_tipo_examen,estado) VALUES ('EEG',100,5,1);
INSERT INTO examenes(nombre,precio,id_tipo_examen,estado) VALUES ('EEG',100,4,1);
INSERT INTO examenes(nombre,precio,id_tipo_examen,estado) VALUES ('EEG Portatil',100,1,1);
INSERT INTO examenes(nombre,precio,id_tipo_examen,estado) VALUES ('EEG Portatil',100,3,1);
INSERT INTO examenes(nombre,precio,id_tipo_examen,estado) VALUES ('EEG p�rtatil  2 hrs.',100,3,1);
INSERT INTO examenes(nombre,precio,id_tipo_examen,estado) VALUES ('EEG Portatil',100,2,1);
INSERT INTO examenes(nombre,precio,id_tipo_examen,estado) VALUES ('EEG Port�til',100,4,1);
INSERT INTO examenes(nombre,precio,id_tipo_examen,estado) VALUES ('EEG',100,6,1);
INSERT INTO examenes(nombre,precio,id_tipo_examen,estado) VALUES ('EEG',100,7,1);
INSERT INTO examenes(nombre,precio,id_tipo_examen,estado) VALUES ('Electroencefalograma',100,1,1);
INSERT INTO examenes(nombre,precio,id_tipo_examen,estado) VALUES ('Electroencefalograma Video (2 horas)',100,7,1);
INSERT INTO examenes(nombre,precio,id_tipo_examen,estado) VALUES ('Electromiograma del Nervio Facial Izquierdo',100,8,1);
INSERT INTO examenes(nombre,precio,id_tipo_examen,estado) VALUES ('Electromiograma miembro superiores Seguros',100,7,1);
INSERT INTO examenes(nombre,precio,id_tipo_examen,estado) VALUES ('Electromiograma miembros inferiores Seguros',100,7,1);
INSERT INTO examenes(nombre,precio,id_tipo_examen,estado) VALUES ('Electromiograma Nervio Facial Derecho',100,8,1);
INSERT INTO examenes(nombre,precio,id_tipo_examen,estado) VALUES ('EMG',100,2,1);
INSERT INTO examenes(nombre,precio,id_tipo_examen,estado) VALUES ('EMG 1 Extremidad',100,1,1);
INSERT INTO examenes(nombre,precio,id_tipo_examen,estado) VALUES ('EMG DE 2 miembros',100,4,1);
INSERT INTO examenes(nombre,precio,id_tipo_examen,estado) VALUES ('EMG de musculos paravertebrales cervicales',100,4,1);
INSERT INTO examenes(nombre,precio,id_tipo_examen,estado) VALUES ('EMG Etremidad Inferior Bilateral',100,8,1);
INSERT INTO examenes(nombre,precio,id_tipo_examen,estado) VALUES ('EMG Exonerado',100,5,1);
INSERT INTO examenes(nombre,precio,id_tipo_examen,estado) VALUES ('EMG Extremidad Inferior Bilateral',100,3,1);
INSERT INTO examenes(nombre,precio,id_tipo_examen,estado) VALUES ('EMG Extremidad Inferior derecha',100,8,1);
INSERT INTO examenes(nombre,precio,id_tipo_examen,estado) VALUES ('EMG Extremidad Inferior Izquierda',100,8,1);
INSERT INTO examenes(nombre,precio,id_tipo_examen,estado) VALUES ('EMG Extremidad Superior Bilateral',100,6,1);
INSERT INTO examenes(nombre,precio,id_tipo_examen,estado) VALUES ('EMG Extremidades Superiores e Inferiores',100,8,1);
INSERT INTO examenes(nombre,precio,id_tipo_examen,estado) VALUES ('EMG Extremindad Superior Bilateral',100,3,1);
INSERT INTO examenes(nombre,precio,id_tipo_examen,estado) VALUES ('EMG',100,3,1);
INSERT INTO examenes(nombre,precio,id_tipo_examen,estado) VALUES ('EMG',100,4,1);
INSERT INTO examenes(nombre,precio,id_tipo_examen,estado) VALUES ('EMG IGSS Extremidad  Superior Bialteral',100,8,1);
INSERT INTO examenes(nombre,precio,id_tipo_examen,estado) VALUES ('EMG Miembros Superiores',100,7,1);
INSERT INTO examenes(nombre,precio,id_tipo_examen,estado) VALUES ('EMG Nervio Facial Bilateral',100,4,1);
INSERT INTO examenes(nombre,precio,id_tipo_examen,estado) VALUES ('EMG Nervio Facial Derecho',100,4,1);
INSERT INTO examenes(nombre,precio,id_tipo_examen,estado) VALUES ('EMG Nervio Facial Izquierdo',100,4,1);
INSERT INTO examenes(nombre,precio,id_tipo_examen,estado) VALUES ('EMG nervio pudeno',100,8,1);
INSERT INTO examenes(nombre,precio,id_tipo_examen,estado) VALUES ('EMG Paravertebrales Lumbares',100,4,1);
INSERT INTO examenes(nombre,precio,id_tipo_examen,estado) VALUES ('EMG Port�til',100,2,1);
INSERT INTO examenes(nombre,precio,id_tipo_examen,estado) VALUES ('EMG Port�til',100,3,1);
INSERT INTO examenes(nombre,precio,id_tipo_examen,estado) VALUES ('EMG y Velocidad de Conduccion Nerviosa',100,4,1);
INSERT INTO examenes(nombre,precio,id_tipo_examen,estado) VALUES ('Estimulacion Magnetica (TMS)',100,8,1);
INSERT INTO examenes(nombre,precio,id_tipo_examen,estado) VALUES ('Estimulacion Magnetica (TMS)*Sesion',100,8,1);
INSERT INTO examenes(nombre,precio,id_tipo_examen,estado) VALUES ('Estimulacion repetitiva',100,8,1);
INSERT INTO examenes(nombre,precio,id_tipo_examen,estado) VALUES ('IGSS EMG y Velocidad de conduccion Nerviosa',100,8,1);
INSERT INTO examenes(nombre,precio,id_tipo_examen,estado) VALUES ('IGSS MacroEMG Extremidad inferior bilateral',100,8,1);
INSERT INTO examenes(nombre,precio,id_tipo_examen,estado) VALUES ('Mapeo Cerebal',100,1,1);
INSERT INTO examenes(nombre,precio,id_tipo_examen,estado) VALUES ('Mapeo Cerebral',100,2,1);
INSERT INTO examenes(nombre,precio,id_tipo_examen,estado) VALUES ('Mapeo Cerebral',100,3,1);
INSERT INTO examenes(nombre,precio,id_tipo_examen,estado) VALUES ('Narcolepsia - Test de latencias multiples',100,4,1);
INSERT INTO examenes(nombre,precio,id_tipo_examen,estado) VALUES ('P. cognitivo P300',100,1,1);
INSERT INTO examenes(nombre,precio,id_tipo_examen,estado) VALUES ('P. cognitivo P300',100,2,1);
INSERT INTO examenes(nombre,precio,id_tipo_examen,estado) VALUES ('P. cognitivo P300',100,3,1);
INSERT INTO examenes(nombre,precio,id_tipo_examen,estado) VALUES ('P. cognitivo P300',100,5,1);
INSERT INTO examenes(nombre,precio,id_tipo_examen,estado) VALUES ('P. E. Auditivos',100,1,1);
INSERT INTO examenes(nombre,precio,id_tipo_examen,estado) VALUES ('P. E. Auditivos',100,2,1);
INSERT INTO examenes(nombre,precio,id_tipo_examen,estado) VALUES ('P. E. Auditivos',100,3,1);
INSERT INTO examenes(nombre,precio,id_tipo_examen,estado) VALUES ('P. E. Auditivos',100,5,1);
INSERT INTO examenes(nombre,precio,id_tipo_examen,estado) VALUES ('P. E. Visuales',100,5,1);
INSERT INTO examenes(nombre,precio,id_tipo_examen,estado) VALUES ('P. E. Visuales',100,7,1);
INSERT INTO examenes(nombre,precio,id_tipo_examen,estado) VALUES ('P. Sensoriales',100,1,1);
INSERT INTO examenes(nombre,precio,id_tipo_examen,estado) VALUES ('P. Sensoriales',100,2,1);
INSERT INTO examenes(nombre,precio,id_tipo_examen,estado) VALUES ('P. Sensoriales',100,3,1);
INSERT INTO examenes(nombre,precio,id_tipo_examen,estado) VALUES ('P. Somatosensoriales',100,1,1);
INSERT INTO examenes(nombre,precio,id_tipo_examen,estado) VALUES ('P. Somatosensoriales',100,5,1);
INSERT INTO examenes(nombre,precio,id_tipo_examen,estado) VALUES ('P. Somatosensoriales miembros Inferiores',100,4,1);
INSERT INTO examenes(nombre,precio,id_tipo_examen,estado) VALUES ('P. Somatosensoriales Nervio Pudeno',100,8,1);
INSERT INTO examenes(nombre,precio,id_tipo_examen,estado) VALUES ('P.E Auditivos',100,4,1);
INSERT INTO examenes(nombre,precio,id_tipo_examen,estado) VALUES ('P.E. Somatosensoriales miembros superiores',100,4,1);
INSERT INTO examenes(nombre,precio,id_tipo_examen,estado) VALUES ('P.E. Visuales',100,1,1);
INSERT INTO examenes(nombre,precio,id_tipo_examen,estado) VALUES ('P.E. Visuales',100,2,1);
INSERT INTO examenes(nombre,precio,id_tipo_examen,estado) VALUES ('P.E. Visuales',100,3,1);
INSERT INTO examenes(nombre,precio,id_tipo_examen,estado) VALUES ('P.E. Visuales con Damero',100,2,1);
INSERT INTO examenes(nombre,precio,id_tipo_examen,estado) VALUES ('P.E. Visuales con Damero',100,3,1);
INSERT INTO examenes(nombre,precio,id_tipo_examen,estado) VALUES ('P.E. Visuales con Damero',100,5,1);
INSERT INTO examenes(nombre,precio,id_tipo_examen,estado) VALUES ('P.E. Visuales',100,4,1);
INSERT INTO examenes(nombre,precio,id_tipo_examen,estado) VALUES ('P.E. Visuales',100,4,1);
INSERT INTO examenes(nombre,precio,id_tipo_examen,estado) VALUES ('Poligrafia Respiratoria',100,1,1);
INSERT INTO examenes(nombre,precio,id_tipo_examen,estado) VALUES ('Poligrafia Respitaroria',100,2,1);
INSERT INTO examenes(nombre,precio,id_tipo_examen,estado) VALUES ('Poligrafia Respitatoria',100,3,1);
INSERT INTO examenes(nombre,precio,id_tipo_examen,estado) VALUES ('Potenciales Evocados Auditivos',100,8,1);
INSERT INTO examenes(nombre,precio,id_tipo_examen,estado) VALUES ('Potenciales Somatosensoriales',100,4,1);
INSERT INTO examenes(nombre,precio,id_tipo_examen,estado) VALUES ('PSG',100,2,1);
INSERT INTO examenes(nombre,precio,id_tipo_examen,estado) VALUES ('PSG',100,3,1);
INSERT INTO examenes(nombre,precio,id_tipo_examen,estado) VALUES ('PSG',100,5,1);
INSERT INTO examenes(nombre,precio,id_tipo_examen,estado) VALUES ('PSG (Polisonografia)',100,8,1);
INSERT INTO examenes(nombre,precio,id_tipo_examen,estado) VALUES ('PSG',100,1,1);
INSERT INTO examenes(nombre,precio,id_tipo_examen,estado) VALUES ('Video EEG DE 12 Horas',100,4,1);
