INSERT INTO medicamentos(nombre,codigo,existencia_total,precio_costo,precio_publico,estado) VALUES ('Mascarilla Unidad','Pendiente',5000,50,100,1);
INSERT INTO medicamentos(nombre,codigo,existencia_total,precio_costo,precio_publico,estado) VALUES ('Baclogerd 10mg * 30 tabletas','Pendiente',5000,50,100,1);
INSERT INTO medicamentos(nombre,codigo,existencia_total,precio_costo,precio_publico,estado) VALUES ('Gabex 300MG*30','Pendiente',5000,50,100,1);
INSERT INTO medicamentos(nombre,codigo,existencia_total,precio_costo,precio_publico,estado) VALUES ('Electrodo Adesivo Redondo 2pul','Pendiente',5000,50,100,1);
INSERT INTO medicamentos(nombre,codigo,existencia_total,precio_costo,precio_publico,estado) VALUES ('Electrodo autoadesivo Retangular 2x3.5pul','Pendiente',5000,50,100,1);
INSERT INTO medicamentos(nombre,codigo,existencia_total,precio_costo,precio_publico,estado) VALUES ('Tegretol CR 400mg','Pendiente',5000,50,100,1);
INSERT INTO medicamentos(nombre,codigo,existencia_total,precio_costo,precio_publico,estado) VALUES ('Rivotril 2.5mg*10ml','Pendiente',5000,50,100,1);
INSERT INTO medicamentos(nombre,codigo,existencia_total,precio_costo,precio_publico,estado) VALUES ('Electrodo Adesivo Redondo 1.25PUL','Pendiente',5000,50,100,1);
INSERT INTO medicamentos(nombre,codigo,existencia_total,precio_costo,precio_publico,estado) VALUES ('Electrodos para Fisioterapia','Pendiente',5000,50,100,1);
INSERT INTO medicamentos(nombre,codigo,existencia_total,precio_costo,precio_publico,estado) VALUES ('Gastroflux 10mg * 30 tabletas','Pendiente',5000,50,100,1);
INSERT INTO medicamentos(nombre,codigo,existencia_total,precio_costo,precio_publico,estado) VALUES ('Asmara Relax Blister 10 tabletas','Pendiente',5000,50,100,1);
INSERT INTO medicamentos(nombre,codigo,existencia_total,precio_costo,precio_publico,estado) VALUES ('Lacotem 100 mg * 28 Comprimidos','Pendiente',5000,50,100,1);
INSERT INTO medicamentos(nombre,codigo,existencia_total,precio_costo,precio_publico,estado) VALUES ('Zetawin Forte 1 gramo x 10 tabletas','Pendiente',5000,50,100,1);
INSERT INTO medicamentos(nombre,codigo,existencia_total,precio_costo,precio_publico,estado) VALUES ('Nucleo C.M.P Forte C*30 CAP','Pendiente',5000,50,100,1);
INSERT INTO medicamentos(nombre,codigo,existencia_total,precio_costo,precio_publico,estado) VALUES ('Topical 100mg','Pendiente',5000,50,100,1);
INSERT INTO medicamentos(nombre,codigo,existencia_total,precio_costo,precio_publico,estado) VALUES ('Cardioaspirina 81mg * 30 tab','Pendiente',5000,50,100,1);
INSERT INTO medicamentos(nombre,codigo,existencia_total,precio_costo,precio_publico,estado) VALUES ('Asmara 400mg blister 4 tabletas','Pendiente',5000,50,100,1);
INSERT INTO medicamentos(nombre,codigo,existencia_total,precio_costo,precio_publico,estado) VALUES ('Zetawin Forte 1 gramo X 20 TAB','Pendiente',5000,50,100,1);
INSERT INTO medicamentos(nombre,codigo,existencia_total,precio_costo,precio_publico,estado) VALUES ('Kopodex 1000mg *30 comprimidos','Pendiente',5000,50,100,1);
INSERT INTO medicamentos(nombre,codigo,existencia_total,precio_costo,precio_publico,estado) VALUES ('Kinesiotape 1 metro','Pendiente',5000,50,100,1);
INSERT INTO medicamentos(nombre,codigo,existencia_total,precio_costo,precio_publico,estado) VALUES ('Cetamin CC*30','Pendiente',5000,50,100,1);
INSERT INTO medicamentos(nombre,codigo,existencia_total,precio_costo,precio_publico,estado) VALUES ('Tegretol CR200mg blister*20 comprimidos','Pendiente',5000,50,100,1);
INSERT INTO medicamentos(nombre,codigo,existencia_total,precio_costo,precio_publico,estado) VALUES ('Fulcrum 30 comprimidos','Pendiente',5000,50,100,1);
INSERT INTO medicamentos(nombre,codigo,existencia_total,precio_costo,precio_publico,estado) VALUES ('Ceumid IV 500mg x 10 vial','Pendiente',5000,50,100,1);
INSERT INTO medicamentos(nombre,codigo,existencia_total,precio_costo,precio_publico,estado) VALUES ('Deflazacort Gal Suspension X 60ml','Pendiente',5000,50,100,1);
INSERT INTO medicamentos(nombre,codigo,existencia_total,precio_costo,precio_publico,estado) VALUES ('Tegretol Jarabe X100ml','Pendiente',5000,50,100,1);
INSERT INTO medicamentos(nombre,codigo,existencia_total,precio_costo,precio_publico,estado) VALUES ('Escitalopram 20mg 30 tabletas','Pendiente',5000,50,100,1);
INSERT INTO medicamentos(nombre,codigo,existencia_total,precio_costo,precio_publico,estado) VALUES ('Lacotem 50mg * 28 comprimidos','Pendiente',5000,50,100,1);
INSERT INTO medicamentos(nombre,codigo,existencia_total,precio_costo,precio_publico,estado) VALUES ('Martesia Dividosis 75mg * 28 compr.','Pendiente',5000,50,100,1);
INSERT INTO medicamentos(nombre,codigo,existencia_total,precio_costo,precio_publico,estado) VALUES ('Asmara 600mg blister de 10 Cap','Pendiente',5000,50,100,1);
INSERT INTO medicamentos(nombre,codigo,existencia_total,precio_costo,precio_publico,estado) VALUES ('Ceumid 500mg pastilla XR','Pendiente',5000,50,100,1);
INSERT INTO medicamentos(nombre,codigo,existencia_total,precio_costo,precio_publico,estado) VALUES ('Ceumid 100 mg*150ml (soluci�n)','Pendiente',5000,50,100,1);
INSERT INTO medicamentos(nombre,codigo,existencia_total,precio_costo,precio_publico,estado) VALUES ('Epival ER 500mg 30 tab','Pendiente',5000,50,100,1);
INSERT INTO medicamentos(nombre,codigo,existencia_total,precio_costo,precio_publico,estado) VALUES ('Escitalopram pastilla 10mg 30 tab','Pendiente',5000,50,100,1);
INSERT INTO medicamentos(nombre,codigo,existencia_total,precio_costo,precio_publico,estado) VALUES ('Lamotrigina de 25 mg 30 tab','Pendiente',5000,50,100,1);
INSERT INTO medicamentos(nombre,codigo,existencia_total,precio_costo,precio_publico,estado) VALUES ('Lamotrigina de 100mg pastilla','Pendiente',5000,50,100,1);
INSERT INTO medicamentos(nombre,codigo,existencia_total,precio_costo,precio_publico,estado) VALUES ('Equiliv 2.5 solucion','Pendiente',5000,50,100,1);
INSERT INTO medicamentos(nombre,codigo,existencia_total,precio_costo,precio_publico,estado) VALUES ('Equiliv  Pastillas','Pendiente',5000,50,100,1);
INSERT INTO medicamentos(nombre,codigo,existencia_total,precio_costo,precio_publico,estado) VALUES ('Lyveryum 0.5 mg x 30 Tab','Pendiente',5000,50,100,1);
INSERT INTO medicamentos(nombre,codigo,existencia_total,precio_costo,precio_publico,estado) VALUES ('Psicodol 1mg Solucion','Pendiente',5000,50,100,1);
INSERT INTO medicamentos(nombre,codigo,existencia_total,precio_costo,precio_publico,estado) VALUES ('Atemperator 400mg pastilla','Pendiente',5000,50,100,1);
INSERT INTO medicamentos(nombre,codigo,existencia_total,precio_costo,precio_publico,estado) VALUES ('Positiv 50mg  30 tab','Pendiente',5000,50,100,1);
INSERT INTO medicamentos(nombre,codigo,existencia_total,precio_costo,precio_publico,estado) VALUES ('Depakene 120mg solucion','Pendiente',5000,50,100,1);
INSERT INTO medicamentos(nombre,codigo,existencia_total,precio_costo,precio_publico,estado) VALUES ('Hidrato de Cloral','Pendiente',5000,50,100,1);
INSERT INTO medicamentos(nombre,codigo,existencia_total,precio_costo,precio_publico,estado) VALUES ('Medicamentos aplicados en Clinica','Pendiente',5000,50,100,1);
INSERT INTO medicamentos(nombre,codigo,existencia_total,precio_costo,precio_publico,estado) VALUES ('Hidrato de Cloral dosificado','Pendiente',5000,50,100,1);
INSERT INTO medicamentos(nombre,codigo,existencia_total,precio_costo,precio_publico,estado) VALUES ('Asmara Tabletas 800 Blister de 10cap','Pendiente',5000,50,100,1);
INSERT INTO medicamentos(nombre,codigo,existencia_total,precio_costo,precio_publico,estado) VALUES ('Colageno DMA','Pendiente',5000,50,100,1);
INSERT INTO medicamentos(nombre,codigo,existencia_total,precio_costo,precio_publico,estado) VALUES ('Piridoxina DMA','Pendiente',5000,50,100,1);
INSERT INTO medicamentos(nombre,codigo,existencia_total,precio_costo,precio_publico,estado) VALUES ('Dicloflor kids sobre','Pendiente',5000,50,100,1);
INSERT INTO medicamentos(nombre,codigo,existencia_total,precio_costo,precio_publico,estado) VALUES ('Vitamina D 400 ui gotas','Pendiente',5000,50,100,1);
INSERT INTO medicamentos(nombre,codigo,existencia_total,precio_costo,precio_publico,estado) VALUES ('Vitamina D 2,000 ui 60 unidades','Pendiente',5000,50,100,1);
INSERT INTO medicamentos(nombre,codigo,existencia_total,precio_costo,precio_publico,estado) VALUES ('Melatonina capsulas','Pendiente',5000,50,100,1);
INSERT INTO medicamentos(nombre,codigo,existencia_total,precio_costo,precio_publico,estado) VALUES ('Melatonina gotas','Pendiente',5000,50,100,1);
INSERT INTO medicamentos(nombre,codigo,existencia_total,precio_costo,precio_publico,estado) VALUES ('Carnitina Capsula','Pendiente',5000,50,100,1);
INSERT INTO medicamentos(nombre,codigo,existencia_total,precio_costo,precio_publico,estado) VALUES ('Ginkgo biloba','Pendiente',5000,50,100,1);
INSERT INTO medicamentos(nombre,codigo,existencia_total,precio_costo,precio_publico,estado) VALUES ('Coenzima Q10','Pendiente',5000,50,100,1);
INSERT INTO medicamentos(nombre,codigo,existencia_total,precio_costo,precio_publico,estado) VALUES ('L-Glutamina','Pendiente',5000,50,100,1);
INSERT INTO medicamentos(nombre,codigo,existencia_total,precio_costo,precio_publico,estado) VALUES ('Omega DMA','Pendiente',5000,50,100,1);
INSERT INTO medicamentos(nombre,codigo,existencia_total,precio_costo,precio_publico,estado) VALUES ('Arginina','Pendiente',5000,50,100,1);
INSERT INTO medicamentos(nombre,codigo,existencia_total,precio_costo,precio_publico,estado) VALUES ('Ornitina','Pendiente',5000,50,100,1);