INSERT INTO equipo_galo_techs(nombre,codigo,estado,existencia_total,id_tipo_equipo) VALUES ('Electrodo de Tierra (30MMD 0.75 (30) 1.5mm DIN)',1,1,0,1);
INSERT INTO equipo_galo_techs(nombre,codigo,estado,existencia_total,id_tipo_equipo) VALUES ('Sensor de Posicion',2,1,0,1);
INSERT INTO equipo_galo_techs(nombre,codigo,estado,existencia_total,id_tipo_equipo) VALUES ('Banda de hebilla grande/sentido de sue�o',3,1,0,1);
INSERT INTO equipo_galo_techs(nombre,codigo,estado,existencia_total,id_tipo_equipo) VALUES ('Ten 20 (8onz pack 3)',4,1,0,1);
INSERT INTO equipo_galo_techs(nombre,codigo,estado,existencia_total,id_tipo_equipo) VALUES ('Nuprep (4onz pack de 3)',5,1,0,1);
INSERT INTO equipo_galo_techs(nombre,codigo,estado,existencia_total,id_tipo_equipo) VALUES ('Pegatinas cuadradas 30 unidades',6,1,0,1);
INSERT INTO equipo_galo_techs(nombre,codigo,estado,existencia_total,id_tipo_equipo) VALUES ('Micropore 2 Pul Blanco',7,1,0,1);
INSERT INTO equipo_galo_techs(nombre,codigo,estado,existencia_total,id_tipo_equipo) VALUES ('Agujas de Ambu color verde',8,1,0,1);
INSERT INTO equipo_galo_techs(nombre,codigo,estado,existencia_total,id_tipo_equipo) VALUES ('Cable Concentrico Neuroline 100cm/40',9,1,0,1);
INSERT INTO equipo_galo_techs(nombre,codigo,estado,existencia_total,id_tipo_equipo) VALUES ('Electrodo de Tierra para EMG Reutilizable/2853224',10,1,0,1);
INSERT INTO equipo_galo_techs(nombre,codigo,estado,existencia_total,id_tipo_equipo) VALUES ('Pegatinas SNAP bolsa de 50 pegatinas redondas',11,1,0,1);
INSERT INTO equipo_galo_techs(nombre,codigo,estado,existencia_total,id_tipo_equipo) VALUES ('Electrodos (10 unidades) 152cms',12,1,0,1);
INSERT INTO equipo_galo_techs(nombre,codigo,estado,existencia_total,id_tipo_equipo) VALUES ('Ac Cream',13,1,0,1);
INSERT INTO equipo_galo_techs(nombre,codigo,estado,existencia_total,id_tipo_equipo) VALUES ('Electrodos adhesivos (pegatinas) Neuroline 720 25u',14,1,0,1);
INSERT INTO equipo_galo_techs(nombre,codigo,estado,existencia_total,id_tipo_equipo) VALUES ('Agujas para EMG Caja 25 uni.  color Lila',15,1,0,1);
INSERT INTO equipo_galo_techs(nombre,codigo,estado,existencia_total,id_tipo_equipo) VALUES ('Agujas para EMG Caja 25 uni.  color rosado',16,1,0,1);
INSERT INTO equipo_galo_techs(nombre,codigo,estado,existencia_total,id_tipo_equipo) VALUES ('Electrodo  (5 uni) 2.0m*80',17,1,0,1);
INSERT INTO equipo_galo_techs(nombre,codigo,estado,existencia_total,id_tipo_equipo) VALUES ('Kendall Pegatinas * 50 piezas',18,1,0,1);
INSERT INTO equipo_galo_techs(nombre,codigo,estado,existencia_total,id_tipo_equipo) VALUES ('Conector para agujas EMG',19,1,0,1);
INSERT INTO equipo_galo_techs(nombre,codigo,estado,existencia_total,id_tipo_equipo) VALUES ('Agujas de Ambu Color Rosado',20,1,0,1);
INSERT INTO equipo_galo_techs(nombre,codigo,estado,existencia_total,id_tipo_equipo) VALUES ('Termistor sensor de flujo de aire terico oral/nasa',21,1,0,1);
INSERT INTO equipo_galo_techs(nombre,codigo,estado,existencia_total,id_tipo_equipo) VALUES ('Electrodos de (10 unidades 100cms)',22,1,0,1);
INSERT INTO equipo_galo_techs(nombre,codigo,estado,existencia_total,id_tipo_equipo) VALUES ('Pinza Bipolar HN-240 S 0.4 ZZC III',23,1,0,1);
INSERT INTO equipo_galo_techs(nombre,codigo,estado,existencia_total,id_tipo_equipo) VALUES ('Pinza Bipolar HN/230 W0.4 ZXC III',24,1,0,1);
INSERT INTO equipo_galo_techs(nombre,codigo,estado,existencia_total,id_tipo_equipo) VALUES ('Pinza Bipolar HSDN 200 S 0.7 XZ',25,1,0,1);
INSERT INTO equipo_galo_techs(nombre,codigo,estado,existencia_total,id_tipo_equipo) VALUES ('Pinza Bipolar para Cirugia Abta HN/230 W 0.07 XZCI',26,1,0,1);
INSERT INTO equipo_galo_techs(nombre,codigo,estado,existencia_total,id_tipo_equipo) VALUES ('Punta de Tungsteno Telescopic HN-190 DD 0.4 ZZZ II',27,1,0,1);
INSERT INTO equipo_galo_techs(nombre,codigo,estado,existencia_total,id_tipo_equipo) VALUES ('Fresa Desechable de Parada Aut/HM-IV-I 2*95*3',28,1,0,1);
INSERT INTO equipo_galo_techs(nombre,codigo,estado,existencia_total,id_tipo_equipo) VALUES ('Fresa Desechable Cabeza de Sandia/HM-IV-I 2*130*3',29,1,0,1);
INSERT INTO equipo_galo_techs(nombre,codigo,estado,existencia_total,id_tipo_equipo) VALUES ('Equipo de Irrigacion *SUP Desechable HY-I-3.0*170Z',30,1,0,1);
INSERT INTO equipo_galo_techs(nombre,codigo,estado,existencia_total,id_tipo_equipo) VALUES ('Fuente de Poder y Generados Ultrasonico BTW-UT2200',31,1,0,1);
INSERT INTO equipo_galo_techs(nombre,codigo,estado,existencia_total,id_tipo_equipo) VALUES ('Retrac de Cuero Cabelludo Dese 191201 APPENIX I38',32,1,0,1);
INSERT INTO equipo_galo_techs(nombre,codigo,estado,existencia_total,id_tipo_equipo) VALUES ('Pinza Bipolar HSDN-200S0.4XZ',33,1,0,1);
INSERT INTO equipo_galo_techs(nombre,codigo,estado,existencia_total,id_tipo_equipo) VALUES ('Mando Ultrasonico Azul Tijera C Abierta BTW-US-B55',34,1,0,1);
INSERT INTO equipo_galo_techs(nombre,codigo,estado,existencia_total,id_tipo_equipo) VALUES ('MandoUltrasonicoGris TijeraLaparoscopica BTW-US-55',35,1,0,1);
INSERT INTO equipo_galo_techs(nombre,codigo,estado,existencia_total,id_tipo_equipo) VALUES ('Perforador Desechable de Parada Aut HZ-IV11*14',36,1,0,1);
INSERT INTO equipo_galo_techs(nombre,codigo,estado,existencia_total,id_tipo_equipo) VALUES ('Pinza de Mano BLAR de CIG Abierta HN160W0.4ZZZIII',37,1,0,1);
INSERT INTO equipo_galo_techs(nombre,codigo,estado,existencia_total,id_tipo_equipo) VALUES ('Pinza Bipolar HSDN-220 S0.4ZX',38,1,0,1);
INSERT INTO equipo_galo_techs(nombre,codigo,estado,existencia_total,id_tipo_equipo) VALUES ('Tijera Para Cirugia Abierta BTW -US-D55',39,1,0,1);
INSERT INTO equipo_galo_techs(nombre,codigo,estado,existencia_total,id_tipo_equipo) VALUES ('Clip HJQ-I',40,1,0,1);
INSERT INTO equipo_galo_techs(nombre,codigo,estado,existencia_total,id_tipo_equipo) VALUES ('Fresa Desechable HM-I-II 1*170*3',41,1,0,1);
INSERT INTO equipo_galo_techs(nombre,codigo,estado,existencia_total,id_tipo_equipo) VALUES ('Retractores Incision  HQ-I (3*III3*V 2*IV)',42,1,0,1);
INSERT INTO equipo_galo_techs(nombre,codigo,estado,existencia_total,id_tipo_equipo) VALUES ('Retrac Cuero Cabelld Dech Apendix II 28*38',43,1,0,1);
INSERT INTO equipo_galo_techs(nombre,codigo,estado,existencia_total,id_tipo_equipo) VALUES ('Base de Retraccion 201111HQ-I',44,1,0,1);
INSERT INTO equipo_galo_techs(nombre,codigo,estado,existencia_total,id_tipo_equipo) VALUES ('Retrac Cuero Cabelld Dech Appendlx II*28*28',45,1,0,1);
INSERT INTO equipo_galo_techs(nombre,codigo,estado,existencia_total,id_tipo_equipo) VALUES ('RANEY CLIPS GUN SET HJQ-II 210412',46,1,0,1);
INSERT INTO equipo_galo_techs(nombre,codigo,estado,existencia_total,id_tipo_equipo) VALUES ('Raney Clips Gon Set HJQ-III',47,1,0,1);
INSERT INTO equipo_galo_techs(nombre,codigo,estado,existencia_total,id_tipo_equipo) VALUES ('MandoUltrason  GrisTijerasLaparoscopicas BTW-USA55',48,1,0,1);
INSERT INTO equipo_galo_techs(nombre,codigo,estado,existencia_total,id_tipo_equipo) VALUES ('Punta de Tugsteno HN110W 0.4 ZXZ I DES',49,1,0,1);
INSERT INTO equipo_galo_techs(nombre,codigo,estado,existencia_total,id_tipo_equipo) VALUES ('Base de Retraccion 190501 HQ-V',50,1,0,1);
INSERT INTO equipo_galo_techs(nombre,codigo,estado,existencia_total,id_tipo_equipo) VALUES ('Filler BG Seelp',51,1,0,1);
INSERT INTO equipo_galo_techs(nombre,codigo,estado,existencia_total,id_tipo_equipo) VALUES ('kid de 8 Retractores Dif Modelos HQ-I  2IV',52,1,0,1);
INSERT INTO equipo_galo_techs(nombre,codigo,estado,existencia_total,id_tipo_equipo) VALUES ('Retrac Cuello Cabelludo Deb 201111 Appendlx 1 28',53,1,0,1);
INSERT INTO equipo_galo_techs(nombre,codigo,estado,existencia_total,id_tipo_equipo) VALUES ('Perforador Desechable de Parada Aut HZ-IV9*12',54,1,0,1);
INSERT INTO equipo_galo_techs(nombre,codigo,estado,existencia_total,id_tipo_equipo) VALUES ('Perforador Desechable de Parada Aut HZ-IV5*8',55,1,0,1);
INSERT INTO equipo_galo_techs(nombre,codigo,estado,existencia_total,id_tipo_equipo) VALUES ('Fresa Desechable De Parada Aut HX-VII-IX2*45',56,1,0,1);
INSERT INTO equipo_galo_techs(nombre,codigo,estado,existencia_total,id_tipo_equipo) VALUES ('Fresa Desechable de Parada Aut HM-IV-I 2*95*5 ?',57,1,0,1);
INSERT INTO equipo_galo_techs(nombre,codigo,estado,existencia_total,id_tipo_equipo) VALUES ('Tijera de Cirugia Abierta BTW-US-C55',58,1,0,1);
INSERT INTO equipo_galo_techs(nombre,codigo,estado,existencia_total,id_tipo_equipo) VALUES ('Pinza de Mano Bipolar HN200 DS 0.4 ZZZ II DES',59,1,0,1);